# Generated by Django 6.0.4 on 2026-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('add_document_to_application', 'Can add document to application'), ('add_subscription_to_application', 'Can add subscription to application')]},
        ),
        migrations.AddField(
            model_name='consumeronboardingstage',
            name='document_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
