# Generated by Django 6.0.4 on 2026-05-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20260424_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='created_by',
        ),
    ]
